### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by misogl** [lonelyclick/react-loading-bar#2]
Do you plan to publish the new version on npm any time soon? The version there is still 0.0.2 and I would like to use it with react 15.

Thank you.

**Comment by lonelyclick** [comment]
done

**Comment by misogl** [comment]
I checked https://www.npmjs.com/package/react-loading-bar and the latest version is still 0.0.2.

**Comment by lonelyclick** [comment]
sorry, now it's done

**Comment by misogl** [comment]
Thanks.
