### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by martinmacko47** [lonelyclick/react-loading-bar#7]
Now the package has peer dependencies `react@^15.0.0` and `react-dom@^15.0.0`. Could you please relax them to allow for React 16? Or is there something in React 16 that would break `react-loading-bar
`?

**Comment by tracethompson** [comment]
+1

**Comment by lonelyclick** [comment]
done with react-loading-bar@0.0.7 @martinmacko47 @tracethompson
